export const REDUCER_NAME = Object.freeze({
    APP_REDUCER: "APP_REDUCER",
    MODEL_REDUCER: "MODEL_REDUCER",
    MODELS_AXIS_REDUCER:"MODELS_AXIS_REDUCER",
    MODELS_CONTAINER_REDUCER: "MODELS_CONTAINER_REDUCER",
});

